server:
  port: 8086

spring:
  application:
    name: notification
  datasource:
    password: password
    url: jdbc:postgresql://ep-tiny-tooth-anffeeof-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_sAtTcGe0nQj4&sslmode=require&channelBinding=require
    username: levantos
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      boot:
        allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

  flyway:
    locations: classpath:db/migration/notification
    enabled: false

  rabbitmq:
    host: gerbil.rmq.cloudamqp.com
    port: 5671
    username: nowzcfua
    password: FNcdkpb13Pl5H2XS2hIrGLorGCuXHJx0
    virtual-host: nowzcfua
    ssl:
      enabled: true


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    prefer-ip-address: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
